[project]
name = "flocode-python-essentials"
version = "0.1.0"
description = "Essential Python for Engineering"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.30.1",
    "pandas>=2.3.3",
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
]

[tool.uv]
package = false
